version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 60s
      retries: 3
    environment:
      MYSQL_DATABASE: hspylib
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql:rw
    networks:
      - esnet

volumes:
  mysql-data:
    driver: local

networks:
  esnet:
