theme: jekyll-theme-leap-day
blank_issues_enabled: false
contact_links:
  - name: HSPyLib Support
    url: https://gitter.im/yorevs-hspylib/community/
    about: Please ask and answer questions here.
