version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: hspylib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql:rw

volumes:
  postgres-data:
