version: '3.3'

services:
  postgres:
    image: postgres/postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql:rw

volumes:
  mysql-data:
