version: '3.9'

services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 60s
      retries: 3
    environment:
      POSTGRES_DB: hspylib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql:rw
    networks:
      - esnet

volumes:
  postgres-data:
    driver: local

networks:
  esnet:
