version: '3.7'

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:latest
    restart: on-failure
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    volumes:
      - zookeeper-data:/var/lib/zookeeper:rw
    networks:
      - esnet

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    restart: on-failure
    depends_on:
      - zookeeper
    environment:
      JMX_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - kafka-data:/var/lib/kafka:rw
    networks:
      - esnet

  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:latest
    restart: on-failure
    depends_on:
      - kafka
      - zookeeper
    command: -Dconfig.file=conf/application.conf -Dapplication.home=bin/kafkamanager
    environment:
      ZK_HOSTS: zookeeper
      APPLICATION_SECRET: letmein
    ports:
      - 9000:9000
    networks:
      - esnet

volumes:
  kafka-data:
    driver: local
  zookeeper-data:
    driver: local

networks:
  esnet:
