services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    hostname: mysql
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 60s
      retries: 3
    environment:
      MYSQL_DATABASE: hspylib
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    networks:
      - esnet

networks:
  esnet:
