version: '3.9'

services:
  zookeeper:
    container_name: zookeeper
    image: yorevs/hhs-zookeeper:5.4.0
    hostname: zookeeper
    restart: on-failure
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 60s
      retries: 3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    volumes:
      - zookeeper-data:/var/lib/zookeeper:rw
    networks:
      - esnet
