[bumpver]
current_version = "0.9.11"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "++version {old_version} -> {new_version}"
commit = false
tag = false
push = false

[bumpver.file_patterns]
"bumpver.toml" = ['current_version = "{version}"']
"gradle.properties" = ["app_version = '{version}'"]
"src/main/hqt/.version" = ["{version}"]
"src/main/README.md" = ["release/v{version}/gray"]
