services:

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 60s
      retries: 3
    environment:
      POSTGRES_DB: hspylib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./data/postgres:/var/lib/postgresql:rw
    networks:
      - esnet

networks:
  esnet:
