version: '3.3'

services:
  mysql:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: hspylib
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./data/var/lib/mysql
