version: '3.3'

services:
  mysql:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: hspylib
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql:rw

volumes:
  mysql-data:
    driver: local

networks:
  esnet:
