[bumpver]
current_version = "0.9.85"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "++version {old_version} -> {new_version}"
commit = false
tag = false
push = false

[bumpver.file_patterns]
"bumpver.toml" = ['current_version = "{version}"']
"build-info.properties" = ["app.version = {version}"]
"gradle.properties" = ["app_version = '{version}'"]
"src/main/vault/.version" = ["{version}"]
"src/main/README.md" = ["release/v{version}/gray"]
