name: build
run-name: HSPyLib build - ${{github.run_number}} [@${{ github.actor }}]

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'modules/**'
  fork:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'modules/**'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: ['3.10', '3.11']
        module: [
          "hspylib", "cfman", "clitt", "datasource", "firebase", "hqt", "kafman", "setman", "vault"
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up Python 3.10+
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update PIP
        run: pip install --upgrade pip
      - name: Build HSPyLib modules
        run: ./gradlew "${{ matrix.module }}:clean" "${{ matrix.module }}:installModule" "${{ matrix.module }}:build"
