name: pypi-publish
run-name: HSPyLib pypi-publish [@${{ github.actor }}]

on:
  workflow_dispatch:
    inputs:
      gradle_debug_params:
        description: 'Gradle debug parameters'
        default: ''
        required: false
        type: string
      pypi_env:
        description: 'Publish package to which PyPi instance ?'
        default: 'pypi-test'
        required: true
        type: choice
        options:
          - 'pypi-test'
          - 'pypi-prod'
      module-cfman:
        description: 'Publish CFMan module ?'
        default: false
        required: true
        type: boolean
      module-clitt:
        description: 'Publish Clitt module ?'
        default: false
        required: true
        type: boolean
      module-datasource:
        description: 'Publish Datasource module ?'
        default: false
        required: true
        type: boolean
      module-firebase:
        description: 'Publish Firebase module ?'
        default: false
        required: true
        type: boolean
      module-hqt:
        description: 'Publish HQT module ?'
        default: false
        required: true
        type: boolean
      module-hspylib:
        description: 'Publish HSPyLib module ?'
        default: false
        required: true
        type: boolean
      module-kafman:
        description: 'Publish Kafman module ?'
        default: false
        required: true
        type: boolean
      module-setman:
        description: 'Publish Setman module ?'
        default: false
        required: true
        type: boolean
      module-vault:
        description: 'Publish Vault module ?'
        default: false
        required: true

permissions:
  contents: read

jobs:
  pypi-publish:
    strategy:
      matrix:
        module: [
          "hspylib", "cfman", "clitt",
          "datasource", "firebase", "hqt",
          "kafman", "setman", "vault"
        ]
    runs-on: ubuntu-latest
    environment: ${{ inputs.pypi_env }}
    env:
      PYPI_REPOSITORY: ${{ vars.PYPI_REPOSITORY }}
      PYPI_MODULE_URL: ${{ vars.PYPI_MODULE_URL }}
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.4'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Python tools
      run: ./gradlew installBuildTools ${gradle_debug_params}
    - name: Publish to PyPi
      if:  inputs["${{ matrix.module }}"]
      run: |
        echo "Publishing ${{ matrix.module }} to ${{ inputs.pypi_env }} -> ${{ env.PYPI_REPOSITORY }} ..."


