name: pypi-publish
run-name: HSPyLib pypi-publish [@${{ github.actor }}]

on:
  workflow_dispatch:
    inputs:
      gradle_debug_params:
        description: 'Gradle debug parameters'
        default: ''
        required: false
        type: string
      pypi_env:
        description: 'PyPi instance to publish ?'
        default: 'pypi-test'
        required: true
        type: choice
        options:
          - 'pypi-test'
          - 'pypi-prod'
      module:
        description: 'Which HSPyLib module ?'
        default: 'all'
        required: true
        type: choice
        options:
          - 'all'
          - 'cfman'
          - 'clitt'
          - 'datasource'
          - 'firebase'
          - 'hqt'
          - 'hspylib'
          - 'kafman'
          - 'setman'
          - 'vault'

permissions:
  contents: read

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.pypi_env }}
    env:
      PYPI_REPOSITORY: ${{ vars.PYPI_REPOSITORY }}
      PYPI_MODULE_URL: ${{ vars.PYPI_MODULE_URL }}
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.4'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Python tools
      run: ./gradlew installBuildTools ${gradle_debug_params}
    - name: Publish module to PyPi
      if: ${{ inputs.module != 'all' }}
      run: |
        echo "Publishing ${{ inputs.module }} to ${{ inputs.pypi_env }} -> ${{ env.PYPI_REPOSITORY }}"
        ./gradlew publish pypiShow ${gradle_debug_params}
    - name: Publish all modules to PyPi
      if: ${{ inputs.module == 'all' }}
      run: |
        echo "Publishing all modules to ${{ inputs.pypi_env }} -> ${{ env.PYPI_REPOSITORY }}"
        ./gradlew "${{ inputs.module }}:publish" "${{ inputs.module }}:pypiShow" ${gradle_debug_params}

